import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Provider as ChakraProvider } from "@/components/ui/provider";
import LayoutWrapper from "@/components/layoutWrapper";

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en" className={`${inter.variable}`}>
      <body className="bg-primary-50">
        <ChakraProvider>
          <LayoutWrapper>
            {children}
          </LayoutWrapper>
        </ChakraProvider>
      </body>
    </html>
  );
}
